apiVersion: v1
kind: Pod
metadata:
  name: gazeboServer
  labels:
    name: gazeboServer
spec:
  containers: 
   -  name: gazeboServer
      image: gazebo:gzserver7
      env:
        - name: GAZEBO_HOSTNAME
        - value: gazeboServer
      args:
          - gzserver 
          - "--verbose"