apiVersion: v1
kind: Pod
metadata:
  name: gazebo-server
  labels:
    name: gazebo-server
spec:
  containers: 
   -  name: gazebo-server
      image: gazebo:gzserver7
      env:
        - name: GAZEBO_HOSTNAME
        - value: gazebo-server
      args:
          - gzserver 
          - "--verbose"