apiVersion: v1
kind: Service
metadata: 
  name: gazebo-client
spec:
  clusterIP: None
  ports: 
    - port: 11345
      protocol: TCP
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector: 
    name: gazebo-client
  type: LoadBalancer