apiVersion: v1
kind: Pod
metadata:
  name: gazeboClient
  labels:
    name: gazeboClient
spec:
  containers: 
   -  name: gazeboClient
      image: kapildesh/gzweb7:v1
      env:
        - name: GAZEBO_HOSTNAME
          value: gazeboClient
        - name: GAZEBO_MASTER_URI
          value: http://gazeboServer:11345
      args:
          - npm 
          - start