apiVersion: v1
kind: Pod
metadata:
  name: gazebo-client
  labels:
    name: gazebo-client
spec:
  containers: 
   -  name: gazebo-client
      image: kapildesh/gzweb7:v1
      env:
        - name: GAZEBO_HOSTNAME
          value: gazebo-client
        - name: GAZEBO_MASTER_URI
          value: http://gazebo-server:11345
      args:
          - npm 
          - start
          - "-p"
          - 1234